"""Add status to Assignment

Revision ID: 2238edb2ba01
Revises: <le NOUVEL identifiant de révision ici>
Create Date: 2025-08-27 11:16:43.301732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2238edb2ba01'
down_revision = '<le NOUVEL identifiant de révision ici>'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_performance_record_assignment'))

    with op.batch_alter_table('staff_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_staff_profile_agency'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_agency'))

    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_venue_agency'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_venue_agency'), ['agency_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_agency'), ['agency_id'], unique=False)

    with op.batch_alter_table('staff_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_staff_profile_agency'), ['agency_id'], unique=False)

    with op.batch_alter_table('performance_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_performance_record_assignment'), ['assignment_id'], unique=False)

    # ### end Alembic commands ###
