"""Make venue_id nullable in assignment table

Revision ID: 23753aca7a0e
Revises: cea3972f4100
Create Date: 2025-08-25 00:28:36.749862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23753aca7a0e'
down_revision = 'cea3972f4100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.alter_column('venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.alter_column('venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
