"""Add AgencyContract model

Revision ID: 248320b99ffd
Revises: 6b4a2b580cdf
Create Date: 2025-08-25 11:12:19.576643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '248320b99ffd'
down_revision = '6b4a2b580cdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agency_contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('late_cutoff_time', sa.String(length=5), nullable=False),
    sa.Column('first_minute_penalty', sa.Float(), nullable=False),
    sa.Column('additional_minute_penalty', sa.Float(), nullable=False),
    sa.Column('drink_price', sa.Float(), nullable=False),
    sa.Column('staff_commission', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agency.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'agency_id', name='_contract_name_agency_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agency_contract')
    # ### end Alembic commands ###
