"""baseline from models (local)

Revision ID: 2b5d6a264236
Revises: 
Create Date: 2025-09-07 22:00:34.320285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b5d6a264236'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Étape 1: ajouter la colonne en nullable avec un défaut serveur (sécurise les lignes existantes)
    with op.batch_alter_table('agency', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_deleted', sa.Boolean(), nullable=True, server_default=sa.text('false'))
        )

    # Étape 2: backfill explicite pour les lignes existantes (sécurité)
    op.execute("UPDATE agency SET is_deleted = FALSE WHERE is_deleted IS NULL;")

    # Étape 3: rendre la colonne NOT NULL
    with op.batch_alter_table('agency', schema=None) as batch_op:
        batch_op.alter_column(
            'is_deleted',
            existing_type=sa.Boolean(),
            nullable=False,
            existing_nullable=True
        )

    # Étape 4 (optionnelle): retirer le défaut serveur pour éviter les effets de bord futurs
    with op.batch_alter_table('agency', schema=None) as batch_op:
        batch_op.alter_column(
            'is_deleted',
            server_default=None,
            existing_type=sa.Boolean(),
            existing_nullable=False
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agency', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
