"""Change ongoing to active in assignment status

Revision ID: 2f0c15f1acfc
Revises: 2238edb2ba01
Create Date: 2025-01-27 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f0c15f1acfc'
down_revision = '2238edb2ba01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE assignment SET status = 'active' WHERE status = 'ongoing'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE assignment SET status = 'ongoing' WHERE status = 'active'")
    # ### end Alembic commands ###




