"""Initial database schema

Revision ID: 36914928863c
Revises: 
Create Date: 2025-08-22 12:16:17.287562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36914928863c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.String(length=10), nullable=True),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('nickname', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('instagram', sa.String(length=80), nullable=True),
    sa.Column('facebook', sa.String(length=80), nullable=True),
    sa.Column('line_id', sa.String(length=80), nullable=True),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('photo_url', sa.String(length=200), nullable=True),
    sa.Column('admin_mama_name', sa.String(length=80), nullable=True),
    sa.Column('current_venue', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('preferred_position', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('managed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('archived_staff_name', sa.String(length=100), nullable=True),
    sa.Column('archived_staff_photo', sa.String(length=200), nullable=True),
    sa.Column('venue', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=50), server_default='Dancer', nullable=False),
    sa.Column('contract_type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('base_salary', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['managed_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('arrival_time', sa.Time(), nullable=True),
    sa.Column('departure_time', sa.Time(), nullable=True),
    sa.Column('drinks_sold', sa.Integer(), nullable=True),
    sa.Column('special_commissions', sa.Float(), nullable=True),
    sa.Column('bonus', sa.Float(), nullable=True),
    sa.Column('malus', sa.Float(), nullable=True),
    sa.Column('lateness_penalty', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'record_date', name='uq_assignment_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performance_record')
    op.drop_table('assignment')
    op.drop_table('user')
    op.drop_table('staff_profile')
    # ### end Alembic commands ###
