"""Add role to User model

Revision ID: 69267b32007d
Revises: 2f0c15f1acfc
Create Date: 2025-08-27 17:05:13.901904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69267b32007d'
down_revision = '2f0c15f1acfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False, server_default='admin'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
