"""Remove legacy role_id from User model

Revision ID: a388c8d43df4
Revises: 69267b32007d
Create Date: 2025-08-27 19:50:14.470329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a388c8d43df4'
down_revision = '69267b32007d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_role'), type_='foreignkey')
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_user_role'), 'role', ['role_id'], ['id'])

    # ### end Alembic commands ###
